# Generated by Django 4.1 on 2023-01-08 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_user_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
