# Generated by Django 4.1 on 2023-01-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='images/default.png', null=True, upload_to='profile_pics'),
        ),
    ]
