# Generated by Django 4.1 on 2023-01-08 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0007_userprofile_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='image',
        ),
    ]
