# Generated by Django 4.1 on 2023-01-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0010_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='pp.png', null=True, upload_to=''),
        ),
    ]
