# Generated by Django 4.1 on 2023-01-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0016_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
