# Generated by Django 4.1 on 2022-12-31 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20221230_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created']},
        ),
    ]
