# Generated by Django 4.1 on 2023-01-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_upvote_downvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downvote',
            old_name='post',
            new_name='blog',
        ),
    ]
