# Generated by Django 3.2 on 2022-12-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0003_alter_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
