# Generated by Django 3.2 on 2022-12-29 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0004_alter_room_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['updated']},
        ),
    ]
