# Generated by Django 3.2 on 2022-12-29 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated']},
        ),
    ]
