# Generated by Django 3.2 on 2022-12-30 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blogroom',
        ),
        migrations.AddField(
            model_name='blog',
            name='blogroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogroom_blog', to='blogapp.blogroom'),
            preserve_default=False,
        ),
    ]
