# Generated by Django 3.2 on 2022-12-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='room',
        ),
        migrations.AddField(
            model_name='post',
            name='room',
            field=models.ManyToManyField(related_name='room_post', to='forumapp.Room'),
        ),
    ]
