# Generated by Django 4.1 on 2023-01-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0003_downvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Downvote',
        ),
    ]
