# Generated by Django 4.1 on 2023-01-05 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forumapp', '0005_downvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorpost_upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
